---
- name: Ensure application directory exists
  file:
    path: "{{ app_dir }}"
    state: directory
    mode: '0755'

- name: Copy docker-compose.yml file if it doesn't exist
  copy:
    src: "docker-configs/{{env}}/docker-compose.yml"  # Source in the 'files' directory
    dest: "{{ app_dir }}/docker-compose.yml"
    mode: '0644'
    force: no

- name: Stop and remove existing Docker containers
  command: docker-compose down
  args:
    chdir: "{{ app_dir }}"
  ignore_errors: true  # Ignore errors if docker-compose down doesn't work

- name: Start Docker containers in detached mode
  command: docker-compose up -d
  args:
    chdir: "{{ app_dir }}"

- name: Check the status of Docker containers
  command: docker-compose ps
  args:
    chdir: "{{ app_dir }}"
  register: compose_ps
  changed_when: false

- name: Print Docker Compose status
  debug:
    msg: "{{ compose_ps.stdout }}"